#!/bin/bash
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/SK-N-MC /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GED.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GEE.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/HEK293 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FJO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FJP.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VKT.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/NT2/D1 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VHN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VIH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VHT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VHZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VHB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VHH.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM12875 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EWS.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/H1 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AXU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BAD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AXI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AYA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AVH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AYY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AVT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AZC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AYO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AZZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AWE.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AVY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AXU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AVN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AYI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AXO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AVY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AXU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AVT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AWE.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AWW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AXC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AWK.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AWQ.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/Raji /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ZPE.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ZPO.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/A549 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AJG.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AKM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AIO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AKE.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ALI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ALO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AIU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AKQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AKA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AJM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ALW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AMA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ELU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ELX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AKM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AKX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AII.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AJS.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AJA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AHY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AIC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ALC.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM12865 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EWB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EWD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001HCN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001HCO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001HCP.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/Jurkat_clone_E61 
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM12878 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ASF.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ATR.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ATA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EXC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EXD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ARW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ATA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AUF.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AUS.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EXX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EXZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ATX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ATL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AST.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AUL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ASJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000ARZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EXN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EXP.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/NB4 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FYQ.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/HCT116 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FIM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FIO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VCM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VCU.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/WI38 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GGU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GGV.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GGL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GGM.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/LNCaP_clone_FGC /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FXI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FXJ.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/HepG2 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BEW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BEF.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BFV.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FLH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FLI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BFJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BGM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FMB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FMD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BER.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BEK.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BFC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BGB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BDS.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BGH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BGT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BFO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FLR.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FLS.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/AG09319 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EOU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EOV.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/Panc1 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VJJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GBJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GBL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VIZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VIT.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/K562 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CBL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYR.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BZZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VDQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BXQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BXV.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FWL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FWN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BXQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VDW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BWA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BZZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BVW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYR.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CBP.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BVE.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CAD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BVT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CAO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BVA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BWL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CCC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CBY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000CBQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BUW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BXV.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BZV.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001HTI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001HTL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FWU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FWX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BXD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BWT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BWL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VDK.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BYX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BWY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BXJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VDE.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/MCF-7 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FXQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FXW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VFR.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VFL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VGL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000VGA.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/DND-41 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AOW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000APC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000APO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AQS.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AQG.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AOS.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AQM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000APU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000API.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AQA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000AQY.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/SK-N-SH /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GFB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GFC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GER.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GES.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GFL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GFN.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/Caco-2 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ESK.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ESN.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ESW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ESX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ESB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ESC.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/HeLa-S3 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BDI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BCJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BDI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BCD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BBF.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BBX.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BAZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BCP.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BCJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FKA.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FKB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FKK.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FKL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BBR.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BDB.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FKU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FKW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BBL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF000BCV.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/AG10803 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EPH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EPI.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/HFF-Myc /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FMV.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FMW.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/AG09309 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EOI.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EOJ.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/AG04450 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ENU.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ENW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ENM.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EMY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EMZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ENF.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/H7 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FDW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FDY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FBY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FBZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FEH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FEI.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/AG04449 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EMH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EMJ.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM12868 
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/BJ /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ERP.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ERQ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ERE.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001ERG.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EQT.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EQU.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/WERI-Rb-1 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GFZ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001GGA.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM12864 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EVL.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EVN.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM12866 
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/GM06990 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EUW.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EUY.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EUC.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EUD.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EUO.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EUP.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/BE2C /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EQH.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001EQI.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm
Projector chrom=human_chrom confounder=/mnt/scratch/shared/SG_KIRILL/confounders/HL-60 /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FNJ.wig /mnt/scratch/shared/SG_KIRILL/samples/ENCFF001FNK.wig
rm -rf /mnt/scratch/shared/SG_KIRILL/samples/*.bprof /mnt/scratch/shared/SG_KIRILL/samples/*.prm