#!/bin/bash
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001GYT/@@download/ENCFF001GYT.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001GYU/@@download/ENCFF001GYU.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF798MEL/@@download/ENCFF798MEL.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CIN/@@download/ENCFF000CIN.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CIO/@@download/ENCFF000CIO.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CIP/@@download/ENCFF000CIP.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HJU/@@download/ENCFF001HJU.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HJY/@@download/ENCFF001HJY.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF597YIM/@@download/ENCFF597YIM.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CQE/@@download/ENCFF000CQE.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CQF/@@download/ENCFF000CQF.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CQH/@@download/ENCFF000CQH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HWM/@@download/ENCFF001HWM.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HWN/@@download/ENCFF001HWN.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF671FKH/@@download/ENCFF671FKH.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HVM/@@download/ENCFF001HVM.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HVO/@@download/ENCFF001HVO.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF969GRO/@@download/ENCFF969GRO.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BJZ/@@download/ENCFF000BJZ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BKA/@@download/ENCFF000BKA.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BKD/@@download/ENCFF000BKD.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HOB/@@download/ENCFF001HOB.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HOC/@@download/ENCFF001HOC.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF437IOA/@@download/ENCFF437IOA.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKH/@@download/ENCFF001HKH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKI/@@download/ENCFF001HKI.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF576BTF/@@download/ENCFF576BTF.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HIW/@@download/ENCFF001HIW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HIX/@@download/ENCFF001HIX.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF908OBD/@@download/ENCFF908OBD.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HSY/@@download/ENCFF001HSY.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HSZ/@@download/ENCFF001HSZ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF280SOV/@@download/ENCFF280SOV.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000VKL/@@download/ENCFF000VKL.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000VKO/@@download/ENCFF000VKO.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF676VDZ/@@download/ENCFF676VDZ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HXC/@@download/ENCFF001HXC.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HXD/@@download/ENCFF001HXD.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF421WFD/@@download/ENCFF421WFD.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CCJ/@@download/ENCFF000CCJ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CCL/@@download/ENCFF000CCL.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CCM/@@download/ENCFF000CCM.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HMG/@@download/ENCFF001HMG.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HMH/@@download/ENCFF001HMH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF008DOI/@@download/ENCFF008DOI.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HWX/@@download/ENCFF001HWX.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HWZ/@@download/ENCFF001HWZ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF948UIP/@@download/ENCFF948UIP.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HJK/@@download/ENCFF001HJK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HJL/@@download/ENCFF001HJL.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF033LOS/@@download/ENCFF033LOS.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000AMC/@@download/ENCFF000AMC.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF128SFZ/@@download/ENCFF128SFZ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF849QON/@@download/ENCFF849QON.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKS/@@download/ENCFF001HKS.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKW/@@download/ENCFF001HKW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF293QZV/@@download/ENCFF293QZV.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HPW/@@download/ENCFF001HPW.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HPX/@@download/ENCFF001HPX.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF712TPV/@@download/ENCFF712TPV.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HLF/@@download/ENCFF001HLF.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HLH/@@download/ENCFF001HLH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF667PKS/@@download/ENCFF667PKS.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CFI/@@download/ENCFF000CFI.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CFK/@@download/ENCFF000CFK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CFO/@@download/ENCFF000CFO.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRJ/@@download/ENCFF001HRJ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRK/@@download/ENCFF001HRK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF047NAO/@@download/ENCFF047NAO.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CUQ/@@download/ENCFF000CUQ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CUR/@@download/ENCFF000CUR.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CUS/@@download/ENCFF000CUS.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HQJ/@@download/ENCFF001HQJ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HQK/@@download/ENCFF001HQK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF160XMD/@@download/ENCFF160XMD.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BQJ/@@download/ENCFF000BQJ.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BQK/@@download/ENCFF000BQK.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BQM/@@download/ENCFF000BQM.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BGU/@@download/ENCFF000BGU.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BGV/@@download/ENCFF000BGV.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BGY/@@download/ENCFF000BGY.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRW/@@download/ENCFF001HRW.bam
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRX/@@download/ENCFF001HRX.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF637KZP/@@download/ENCFF637KZP.bam