#!/bin/bash
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001GYU/@@download/ENCFF001GYU.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF972ATQ/@@download/ENCFF972ATQ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF798MEL/@@download/ENCFF798MEL.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF898XQK/@@download/ENCFF898XQK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF090CYH/@@download/ENCFF090CYH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF429XTA/@@download/ENCFF429XTA.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF092GCH/@@download/ENCFF092GCH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKF/@@download/ENCFF001HKF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF597YIM/@@download/ENCFF597YIM.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF552KRT/@@download/ENCFF552KRT.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CQE/@@download/ENCFF000CQE.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF552KRT/@@download/ENCFF552KRT.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF634UTF/@@download/ENCFF634UTF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF870RFE/@@download/ENCFF870RFE.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF518AQJ/@@download/ENCFF518AQJ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CLW/@@download/ENCFF000CLW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF715NGU/@@download/ENCFF715NGU.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CLV/@@download/ENCFF000CLV.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BKI/@@download/ENCFF000BKI.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BKI/@@download/ENCFF000BKI.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF003XTF/@@download/ENCFF003XTF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HOB/@@download/ENCFF001HOB.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HON/@@download/ENCFF001HON.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF357OBP/@@download/ENCFF357OBP.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF683AKU/@@download/ENCFF683AKU.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKH/@@download/ENCFF001HKH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKG/@@download/ENCFF001HKG.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HIX/@@download/ENCFF001HIX.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF908OBD/@@download/ENCFF908OBD.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF188FPI/@@download/ENCFF188FPI.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF947POT/@@download/ENCFF947POT.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HTK/@@download/ENCFF001HTK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF629FKE/@@download/ENCFF629FKE.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF814VRG/@@download/ENCFF814VRG.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000VKO/@@download/ENCFF000VKO.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF519MQF/@@download/ENCFF519MQF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF552ORJ/@@download/ENCFF552ORJ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF746GSV/@@download/ENCFF746GSV.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HXN/@@download/ENCFF001HXN.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CCQ/@@download/ENCFF000CCQ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF244XQF/@@download/ENCFF244XQF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF692GVG/@@download/ENCFF692GVG.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF643VRW/@@download/ENCFF643VRW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF643VRW/@@download/ENCFF643VRW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HMG/@@download/ENCFF001HMG.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HWX/@@download/ENCFF001HWX.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HXF/@@download/ENCFF001HXF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF948UIP/@@download/ENCFF948UIP.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF033LOS/@@download/ENCFF033LOS.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF686TPQ/@@download/ENCFF686TPQ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF336OEL/@@download/ENCFF336OEL.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF024LIF/@@download/ENCFF024LIF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF970LXF/@@download/ENCFF970LXF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF849QON/@@download/ENCFF849QON.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HLJ/@@download/ENCFF001HLJ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HKS/@@download/ENCFF001HKS.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF293QZV/@@download/ENCFF293QZV.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HQI/@@download/ENCFF001HQI.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HQI/@@download/ENCFF001HQI.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF747WXH/@@download/ENCFF747WXH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HLF/@@download/ENCFF001HLF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HLR/@@download/ENCFF001HLR.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HLH/@@download/ENCFF001HLH.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF563PNW/@@download/ENCFF563PNW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CFK/@@download/ENCFF000CFK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF216TIF/@@download/ENCFF216TIF.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRK/@@download/ENCFF001HRK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRK/@@download/ENCFF001HRK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRK/@@download/ENCFF001HRK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000CUZ/@@download/ENCFF000CUZ.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF199WRC/@@download/ENCFF199WRC.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF699UTE/@@download/ENCFF699UTE.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF160XMD/@@download/ENCFF160XMD.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF327YGC/@@download/ENCFF327YGC.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HQK/@@download/ENCFF001HQK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BQK/@@download/ENCFF000BQK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BQK/@@download/ENCFF000BQK.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BQW/@@download/ENCFF000BQW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF749GHL/@@download/ENCFF749GHL.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF115JNM/@@download/ENCFF115JNM.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF000BGV/@@download/ENCFF000BGV.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF001HRX/@@download/ENCFF001HRX.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF831AXW/@@download/ENCFF831AXW.bigWig
wget -P /mnt/scratch/shared/SG_KIRILL/new_control_no_cl https://www.encodeproject.org/files/ENCFF637KZP/@@download/ENCFF637KZP.bigWig